spring.application.name=visioncare

spring.datasource.url=jdbc:postgresql://localhost:5432/visioncare-api
spring.datasource.username=postgres
spring.datasource.password=MEDE#2m4a

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
